spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8
    username: root
    password:

  mail:
    default-encoding: utf-8
    host: outlook.office365.com
    port: 587
    test-connection: true
    protocol: smtp
    username: *********@outlook.com
    password: ********
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          auth: true
          starttls:
            enable: true
            required: true


  redis:
    password:
    database: 0
    port: 6379
    pool:
      max-idle: 10
      min-idle: 0
      max-active: 200
      max-wait: -1
    host: localhost
    timeout: 1000

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-locations: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.github.candyacao.entity

logging:
  level:
    com.github.candyacao.mapper: DEBUG
